"""INC46 T02 — Rule assets: deterministic MUST / MUST_NOT rules from the trace.

The "rules discovered while doing the work" are **extracted from real evidence**
— never generated by a language model. :func:`extract_rules` is a pure function
over (patterns, runs) that emits:

  * ``must``     — ``Y`` was executed before ``X`` in the successful runs
    (``confidence = #{Y before X} / N``);
  * ``must_not`` — tool ``T`` errored in ``≥ min_support`` runs and **never**
    succeeded (``confidence = #{errored} / #{runs that called T}``).

Every rule carries its ``support`` and ``confidence`` (both recomputable) plus
``source_run_ids`` — the evidence runs — so a reviewer can retrace it. The rule
**text** is a fixed template filled with those real numbers; there is no
generative step anywhere in this module (a static scan in the unit suite pins
that: no chat-model import path exists here).

Persistence goes through the additive ``skill_rule_suggestions`` table (migration
``020``) and follows the house tenant discipline — **fail-closed**: an unresolved
tenant reads nothing and writes nothing (never a shared bucket).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from forgeflow.config import get_settings
from forgeflow.repositories.base import new_id, utcnow
from forgeflow.skills.pattern_miner import (
    derive_run_outcome,
    run_id_of,
    step_status,
    step_tool,
)

logger = logging.getLogger(__name__)

__all__ = [
    "RULE_KINDS",
    "RULE_MIN_SUPPORT",
    "RULE_MIN_CONFIDENCE",
    "RuleAsset",
    "RuleStore",
    "extract_rules",
    "persist_rules",
    "list_rules",
    "clear_rule_store",
]

#: The two rule kinds (verbatim; §8 命名口径).
RULE_KINDS: tuple[str, ...] = ("must", "must_not")

#: Minimum evidence base for a rule to be emitted at all.
RULE_MIN_SUPPORT = 2

#: Minimum (recomputable) confidence for a rule to be emitted.
RULE_MIN_CONFIDENCE = 0.8

_ROUND = 6


# --------------------------------------------------------------------------- #
# value object                                                                 #
# --------------------------------------------------------------------------- #
@dataclass
class RuleAsset:
    """One suggested rule with its recomputable evidence."""

    tenant_id: str | None
    pattern_key: str
    rule_kind: str
    rule_text: str
    support: int
    confidence: float
    source_run_ids: list[str] = field(default_factory=list)
    #: Bookkeeping for the persistence layer (additive; not required by the
    #: extractor, which leaves them at their defaults).
    id: str = field(default_factory=new_id)
    status: str = "suggested"
    created_at: datetime = field(default_factory=utcnow)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "pattern_key": self.pattern_key,
            "rule_kind": self.rule_kind,
            "rule_text": self.rule_text,
            "support": self.support,
            "confidence": self.confidence,
            "source_run_ids": list(self.source_run_ids),
            "status": self.status,
            "created_at": self.created_at.isoformat(),
        }


# --------------------------------------------------------------------------- #
# pure extraction                                                              #
# --------------------------------------------------------------------------- #
def _pattern_tools(pattern: Any) -> list[str]:
    tools = pattern.get("tools") if isinstance(pattern, dict) else getattr(pattern, "tools", None)
    return [str(t) for t in (tools or []) if t]


def _pattern_key_of(pattern: Any) -> str:
    if isinstance(pattern, dict):
        return str(pattern.get("key") or "")
    return str(getattr(pattern, "key", "") or "")


def _candidate_tools(patterns: list[Any], runs: list[list[Any]]) -> list[str]:
    """Tool universe: patterns' tools first (discovered order), then any run tool."""
    tools: list[str] = []
    for pattern in patterns or []:
        for tool in _pattern_tools(pattern):
            if tool not in tools:
                tools.append(tool)
    for run in runs or []:
        for step in run:
            tool = step_tool(step)
            if tool and tool not in tools:
                tools.append(tool)
    return tools


def _first_indices(run: list[Any]) -> dict[str, int]:
    """First-appearance index of every tool within one run."""
    first: dict[str, int] = {}
    for position, step in enumerate(run):
        tool = step_tool(step)
        if tool and tool not in first:
            first[tool] = position
    return first


def _pattern_key_for_pair(patterns: list[Any], first: str, second: str) -> str:
    """The key of the first pattern whose tools list ``first`` before ``second``."""
    for pattern in patterns or []:
        tools = _pattern_tools(pattern)
        if first in tools and second in tools and tools.index(first) < tools.index(second):
            return _pattern_key_of(pattern)
    return ""


def _pattern_key_for_tool(patterns: list[Any], tool: str) -> str:
    for pattern in patterns or []:
        if tool in _pattern_tools(pattern):
            return _pattern_key_of(pattern)
    return ""


def _must_rules(
    patterns: list[Any], successful: list[list[Any]], tools: list[str], min_support: int, min_confidence: float
) -> list[RuleAsset]:
    """``MUST 先 Y 后 X`` for every ordered pair that holds across ≥min_confidence of N."""
    total = len(successful)
    if total < min_support:
        return []

    indices = [(_first_indices(run), run) for run in successful]
    rules: list[RuleAsset] = []
    for first in tools:
        for second in tools:
            if first == second:
                continue
            before = [
                run
                for idx, run in indices
                if first in idx and second in idx and idx[first] < idx[second]
            ]
            confidence = len(before) / total
            if confidence < min_confidence:
                continue
            rules.append(
                RuleAsset(
                    tenant_id=None,
                    pattern_key=_pattern_key_for_pair(patterns, first, second),
                    rule_kind="must",
                    rule_text=(
                        f"MUST 先执行 {first} 再执行 {second}"
                        f"（证据：{total} 次成功 run 中 {len(before)} 次满足先后序，"
                        f"confidence={round(confidence, _ROUND):.4f}）"
                    ),
                    support=total,
                    confidence=round(confidence, _ROUND),
                    source_run_ids=[rid for rid in (run_id_of(r) for r in before) if rid],
                )
            )
    return rules


def _must_not_rules(
    patterns: list[Any], runs: list[list[Any]], tools: list[str], min_support: int, min_confidence: float
) -> list[RuleAsset]:
    """``MUST NOT 直接调用 T`` when T errored ≥min_support times and never succeeded."""
    rules: list[RuleAsset] = []
    for tool in tools:
        calls = [run for run in runs if any(step_tool(s) == tool for s in run)]
        errored = [
            run
            for run in calls
            if any(step_tool(s) == tool and step_status(s) == "error" for s in run)
        ]
        succeeded = any(
            step_tool(s) == tool and step_status(s) == "ok" for run in runs for s in run
        )
        if succeeded or len(errored) < min_support:
            continue
        confidence = len(errored) / len(calls) if calls else 0.0
        if confidence < min_confidence:
            continue
        rules.append(
            RuleAsset(
                tenant_id=None,
                pattern_key=_pattern_key_for_tool(patterns, tool),
                rule_kind="must_not",
                rule_text=(
                    f"MUST NOT 直接调用 {tool}"
                    f"（证据：{len(errored)} 次 run 中该工具置 error 且从未成功，"
                    f"error 率={round(confidence, _ROUND):.4f}；除非先修正输入）"
                ),
                support=len(errored),
                confidence=round(confidence, _ROUND),
                source_run_ids=[rid for rid in (run_id_of(r) for r in errored) if rid],
            )
        )
    return rules


def extract_rules(
    patterns: list[Any],
    runs: list[list[Any]],
    *,
    min_support: int,
    min_confidence: float,
) -> list[RuleAsset]:
    """Deterministically extract ``must`` / ``must_not`` rules from real evidence.

    Pure. ``runs`` is a list of runs, each the ordered step list of one run (the
    same shape :func:`forgeflow.skills.pattern_miner.mine_patterns` consumes).
    ``patterns`` supplies the discovered tool universe / pattern keys. Rules are
    returned ``must`` first, then ``must_not``; within each kind the emission
    order is the tool universe order (stable).
    """
    tools = _candidate_tools(patterns, runs)
    successful = [run for run in runs if derive_run_outcome(run) == "success"]
    rules = _must_rules(patterns, successful, tools, min_support, min_confidence)
    rules.extend(_must_not_rules(patterns, runs, tools, min_support, min_confidence))
    return rules


# --------------------------------------------------------------------------- #
# persistence — skill_rule_suggestions (migration 020), tenant fail-closed      #
# --------------------------------------------------------------------------- #
@runtime_checkable
class RuleStore(Protocol):
    """Minimal persistence port for :class:`RuleAsset` rows."""

    async def save(self, tenant_id: str, rules: list[RuleAsset]) -> list[RuleAsset]:
        """Persist (idempotently) ``rules`` for a resolved ``tenant_id``."""

    async def list(self, tenant_id: str, *, limit: int) -> list[RuleAsset]:
        """Return a tenant's rules, newest first."""


#: In-process store for the offline (``memory``) profile.
_MEMORY: dict[str, list[RuleAsset]] = {}


def clear_rule_store() -> None:
    """Reset the in-memory rule store. Test helper only."""
    _MEMORY.clear()


class _MemoryRuleStore:
    """Dict-backed :class:`RuleStore` (offline profile)."""

    async def save(self, tenant_id: str, rules: list[RuleAsset]) -> list[RuleAsset]:
        bucket = _MEMORY.setdefault(tenant_id, [])
        seen = {(r.pattern_key, r.rule_kind, r.rule_text) for r in bucket}
        for rule in rules:
            key = (rule.pattern_key, rule.rule_kind, rule.rule_text)
            if key in seen:  # idempotent, mirroring the SQL ON CONFLICT DO NOTHING
                continue
            seen.add(key)
            bucket.append(rule)
        return rules

    async def list(self, tenant_id: str, *, limit: int) -> list[RuleAsset]:
        rows = list(_MEMORY.get(tenant_id, []))
        rows.sort(key=lambda r: r.created_at, reverse=True)
        return rows[:limit]


class _PgRuleStore:
    """asyncpg-backed :class:`RuleStore` over ``skill_rule_suggestions``."""

    def __init__(self, pool: Any | None = None) -> None:
        self._pool = pool

    async def _get_pool(self) -> Any:
        if self._pool is not None:
            return self._pool
        from forgeflow.database import get_pool

        return await get_pool()

    async def save(self, tenant_id: str, rules: list[RuleAsset]) -> list[RuleAsset]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            for rule in rules:
                await conn.execute(
                    """
                    INSERT INTO skill_rule_suggestions
                      (tenant_id, pattern_key, rule_kind, rule_text, support,
                       confidence, source_run_ids, status)
                    VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
                    ON CONFLICT (tenant_id, pattern_key, rule_kind, rule_text)
                    DO NOTHING
                    """,
                    tenant_id,
                    rule.pattern_key,
                    rule.rule_kind,
                    rule.rule_text,
                    int(rule.support),
                    float(rule.confidence),
                    list(rule.source_run_ids),
                    rule.status,
                )
        return rules

    async def list(self, tenant_id: str, *, limit: int) -> list[RuleAsset]:
        pool = await self._get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT id, tenant_id, pattern_key, rule_kind, rule_text, support,
                       confidence, source_run_ids, status, created_at
                FROM skill_rule_suggestions
                WHERE tenant_id IS NOT DISTINCT FROM $1
                ORDER BY created_at DESC
                LIMIT $2
                """,
                tenant_id,
                int(limit),
            )
        return [_row_to_rule(r) for r in rows]


def _row_to_rule(row: Any) -> RuleAsset:
    d = dict(row)
    source = d.get("source_run_ids")
    created = d.get("created_at")
    return RuleAsset(
        tenant_id=str(d["tenant_id"]) if d.get("tenant_id") else None,
        pattern_key=str(d.get("pattern_key") or ""),
        rule_kind=str(d.get("rule_kind") or "must"),
        rule_text=str(d.get("rule_text") or ""),
        support=int(d.get("support") or 0),
        confidence=float(d.get("confidence") or 0.0),
        source_run_ids=[str(x) for x in (source or [])],
        id=str(d["id"]) if d.get("id") is not None else new_id(),
        status=str(d.get("status") or "suggested"),
        created_at=created if isinstance(created, datetime) else utcnow(),
    )


def _resolve_store(repo: Any | None) -> Any:
    """The store to use: an injected one, else postgres, else the memory store."""
    if repo is not None:
        return repo
    try:
        backend = str(getattr(get_settings(), "storage_backend", "") or "").lower()
    except Exception:  # noqa: BLE001 — a gate read must never break persistence
        backend = ""
    if backend == "postgres":
        return _PgRuleStore()
    return _MemoryRuleStore()


async def persist_rules(
    tenant_id: str | None, rules: list[RuleAsset], *, repo: Any | None = None
) -> list[RuleAsset]:
    """Persist ``rules`` for ``tenant_id`` — idempotent, **tenant fail-closed**.

    An unresolved tenant writes nothing (returns ``[]``) — the platform never
    invents a ``"default"`` owner for a rule with no tenant.
    """
    if not tenant_id or not rules:
        return []
    for rule in rules:
        rule.tenant_id = tenant_id
    store = _resolve_store(repo)
    return await store.save(tenant_id, rules)


async def list_rules(tenant_id: str | None, *, limit: int = 50) -> list[RuleAsset]:
    """List a tenant's rules, newest first (fail-closed: unresolved ⇒ ``[]``)."""
    if not tenant_id:
        return []
    store = _resolve_store(None)
    return await store.list(tenant_id, limit=limit)
