{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgeflow.secretName" . }}
  labels:
    {{- include "forgeflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
