"""Pydantic domain models for the Sales Operations workflow."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, field_validator


class IndustrySector(StrEnum):
    SAAS = "saas"
    FINTECH = "fintech"
    HEALTHCARE = "healthcare"
    ENTERPRISE = "enterprise"
    ECOMMERCE = "ecommerce"
    MARTECH = "martech"
    OTHER = "other"


class LeadStatus(StrEnum):
    RAW = "raw"
    QUALIFIED = "qualified"
    DISQUALIFIED = "disqualified"
    PROPOSED = "proposed"
    WON = "won"
    LOST = "lost"


class LeadInput(BaseModel):
    """Input model for triggering a new sales ops workflow."""

    company_name: str = Field(..., min_length=1, max_length=256)
    contact_name: str | None = None
    contact_email: str | None = None
    industry: IndustrySector | None = None
    known_budget_usd: int | None = Field(None, ge=0, description="Self-reported budget")
    additional_context: str | None = Field(None, max_length=1000)

    @field_validator("company_name")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


class QualificationResult(BaseModel):
    """Output from the Analyzer agent."""

    score: float = Field(ge=0.0, le=10.0)
    qualified: bool
    icp_fit_reasons: list[str]
    risk_flags: list[str]
    recommended_action: str  # high_priority | standard_proposal | nurture | disqualify
    estimated_deal_value_usd: int = Field(ge=0)
    confidence: float = Field(ge=0.0, le=1.0)
    company: str | None = None


class PricingTier(BaseModel):
    name: str           # Starter | Growth | Enterprise
    price_usd_monthly: int
    features: list[str]
    recommended: bool = False


class Proposal(BaseModel):
    """Full proposal document generated by the Executor agent."""

    proposal_id: str
    lead_id: str | None
    company: str
    executive_summary: str
    pain_points_addressed: list[str]
    solution_overview: str
    pricing_tiers: list[PricingTier | dict]
    expected_roi: str
    next_steps: list[str]
    estimated_deal_value_usd: int
    status: str = "pending_approval"
